### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by alecandido** [NNPDF/mcpdf#1]
Roadmap for closure and actual data implementation.

- [x] 0: PDF level fake data (PDF uncertainty)
- [ ] 1: closure test data through actual DIS theory (PDF uncertainty)
- [x] 2: actual data (actual covmat)
